# Chart Releaser Configuration
# See: https://github.com/helm/chart-releaser/blob/main/README.md#configuration

# GitHub repository settings
owner: kenchrcum
repo: grafana-dashboard-converter
git-repo: https://github.com/kenchrcum/grafana-dashboard-converter

# Chart directory
path: helm

# GitHub Pages settings
pages-branch: gh-pages
pages-index-path: index.yaml

# Release settings
charts-repo-url: https://github.com/kenchrcum/grafana-dashboard-converter/releases
release-name-template: "{{ .Name }}-{{ .Version }}"
index-name: index.yaml

# Options
prerelease: false
packages-with-index: true
debug: true
