# Chart Releaser Configuration
# See: https://github.com/helm/chart-releaser/blob/main/README.md#configuration

# GitHub repository settings
owner: ${{ github.repository_owner }}
repo: ${{ github.event.repository.name }}
git-repo: https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}

# Chart directory
path: helm

# GitHub Pages settings
pages-branch: gh-pages
pages-index-path: index.yaml

# Release settings
charts-repo-url: https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/releases
release-name-template: "{{ .Name }}-{{ .Version }}"
index-name: index.yaml

# Options
prerelease: false
packages-with-index: true
debug: false
