apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dashboard-converter
  namespace: default
  labels:
    app: grafana-dashboard-converter
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-dashboard-converter
  template:
    metadata:
      labels:
        app: grafana-dashboard-converter
        version: v1.0.0
    spec:
      serviceAccountName: grafana-dashboard-converter
      containers:
      - name: converter
        image: kenchrcum/grafana-dashboard-converter:latest
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 10001
      restartPolicy: Always
