name: Setup GitHub Pages

on:
  workflow_dispatch:
    inputs:
      create_gh_pages:
        description: 'Create gh-pages branch for Helm repository'
        required: true
        default: true
        type: boolean

permissions:
  contents: write
  pages: write

jobs:
  setup-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initial commit for GitHub Pages"
          git push origin gh-pages

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create initial index.yaml
        run: |
          mkdir -p charts
          cat > index.yaml << 'EOF'
          apiVersion: v1
          entries: {}
          generated: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          EOF
          git add .
          git commit -m "Add initial Helm repository index"
          git push origin gh-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
